"""initial schema

Revision ID: 4323e2afdd13
Revises: 
Create Date: 2026-08-03 04:30:47.128676
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4323e2afdd13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('homepage', sa.String(length=1000), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('id_stability', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("id_stability IN ('persistent', 'unstable', 'none')", name=op.f('ck_checklist_id_stability')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist')),
    sa.UniqueConstraint('code', name=op.f('uq_checklist_code'))
    )
    op.create_table('name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=1000), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('authorship', sa.String(length=500), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('rank_marker', sa.String(length=20), nullable=True),
    sa.Column('genus', sa.String(length=200), nullable=True),
    sa.Column('specific_epithet', sa.String(length=200), nullable=True),
    sa.Column('infraspecific_epithet', sa.String(length=200), nullable=True),
    sa.Column('nomenclatural_code', sa.String(length=20), nullable=False),
    sa.Column('norm_key', sa.String(length=600), nullable=False),
    sa.Column('canonical_key', sa.String(length=500), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('parse_quality', sa.Integer(), nullable=True),
    sa.Column('parse_warnings', sa.Text(), nullable=True),
    sa.CheckConstraint("nomenclatural_code IN ('botanical', 'zoological', 'bacterial', 'viral', 'unknown')", name=op.f('ck_name_nom_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name')),
    sa.UniqueConstraint('norm_key', name=op.f('uq_name_norm_key'))
    )
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.create_index('ix_name_canonical', ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_name_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index('ix_name_genus_epithet', ['genus', 'specific_epithet'], unique=False)
        batch_op.create_index(batch_op.f('ix_name_rank'), ['rank'], unique=False)

    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name_id', sa.Integer(), nullable=False),
    sa.Column('to_name_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relation IN ('fuzzy_match', 'congruent', 'includes', 'included_in', 'overlaps', 'disjoint')", name=op.f('ck_link_relation')),
    sa.CheckConstraint('from_name_id != to_name_id', name=op.f('ck_link_no_self_link')),
    sa.ForeignKeyConstraint(['from_name_id'], ['name.id'], name=op.f('fk_link_from_name_id_name'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_name_id'], ['name.id'], name=op.f('fk_link_to_name_id_name'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link')),
    sa.UniqueConstraint('from_name_id', 'to_name_id', 'relation', name=op.f('uq_link_from_name_id_to_name_id_relation'))
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_from_name_id'), ['from_name_id'], unique=False)
        batch_op.create_index('ix_link_to_name', ['to_name_id'], unique=False)

    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('released_on', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("format IN ('dwca', 'csv', 'xlsx')", name=op.f('ck_release_format')),
    sa.CheckConstraint("status IN ('importing', 'ready', 'failed')", name=op.f('ck_release_status')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name=op.f('fk_release_checklist_id_checklist'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release')),
    sa.UniqueConstraint('checklist_id', 'version', name=op.f('uq_release_checklist_id_version'))
    )
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index('ix_release_checklist_ordered', ['checklist_id', 'released_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_source_sha256'), ['source_sha256'], unique=False)

    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('anchor_kind', sa.String(length=20), nullable=False),
    sa.Column('anchor_key', sa.String(length=600), nullable=False),
    sa.CheckConstraint("anchor_kind IN ('source_id', 'name')", name=op.f('ck_track_anchor_kind')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name=op.f('fk_track_checklist_id_checklist'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track')),
    sa.UniqueConstraint('checklist_id', 'anchor_kind', 'anchor_key', name=op.f('uq_track_checklist_id_anchor_kind_anchor_key'))
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('source_taxon_id', sa.String(length=200), nullable=True),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('accepted_usage_id', sa.Integer(), nullable=True),
    sa.Column('parent_usage_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('vernacular', sa.JSON(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('accepted', 'synonym', 'ambiguous_synonym', 'misapplied', 'provisional', 'bare_name', 'unknown')", name=op.f('ck_usage_status')),
    sa.ForeignKeyConstraint(['accepted_usage_id'], ['usage.id'], name=op.f('fk_usage_accepted_usage_id_usage'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['name_id'], ['name.id'], name=op.f('fk_usage_name_id_name')),
    sa.ForeignKeyConstraint(['parent_usage_id'], ['usage.id'], name=op.f('fk_usage_parent_usage_id_usage'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], name=op.f('fk_usage_release_id_release'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage')),
    sa.UniqueConstraint('release_id', 'source_taxon_id', name=op.f('uq_usage_release_id_source_taxon_id'))
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index('ix_usage_accepted', ['accepted_usage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_name_id'), ['name_id'], unique=False)
        batch_op.create_index('ix_usage_parent', ['parent_usage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_release_id'), ['release_id'], unique=False)
        batch_op.create_index('ix_usage_release_name', ['release_id', 'name_id'], unique=False)
        batch_op.create_index('ix_usage_release_status', ['release_id', 'status'], unique=False)

    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('from_release_id', sa.Integer(), nullable=False),
    sa.Column('to_release_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('from_usage_id', sa.Integer(), nullable=True),
    sa.Column('to_usage_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("type IN ('added', 'removed', 'renamed', 'author_changed', 'status_changed', 'accepted_changed', 'reclassified', 'rank_changed', 'lumped', 'split', 'id_replaced', 'probable_rename')", name=op.f('ck_change_type')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name=op.f('fk_change_checklist_id_checklist'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_release_id'], ['release.id'], name=op.f('fk_change_from_release_id_release'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_usage_id'], ['usage.id'], name=op.f('fk_change_from_usage_id_usage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_release_id'], ['release.id'], name=op.f('fk_change_to_release_id_release'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_usage_id'], ['usage.id'], name=op.f('fk_change_to_usage_id_usage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name=op.f('fk_change_track_id_track'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change'))
    )
    with op.batch_alter_table('change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index('ix_change_pair', ['from_release_id', 'to_release_id'], unique=False)
        batch_op.create_index('ix_change_pair_type', ['from_release_id', 'to_release_id', 'type'], unique=False)
        batch_op.create_index('ix_change_track', ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_type'), ['type'], unique=False)

    op.create_table('usage_track',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], name=op.f('fk_usage_track_release_id_release'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name=op.f('fk_usage_track_track_id_track'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_id'], ['usage.id'], name=op.f('fk_usage_track_usage_id_usage'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('pk_usage_track')),
    sa.UniqueConstraint('track_id', 'release_id', name=op.f('uq_usage_track_track_id_release_id'))
    )
    with op.batch_alter_table('usage_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_track_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_track_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###
    _create_name_fts()


# --------------------------------------------------------------------------
# FTS5 index over name.canonical_name.
#
# Hand-written because Alembic cannot autogenerate virtual tables. It is an
# external-content index (content='name'), so the text is stored once in `name`
# and FTS5 keeps only the inverted index — but that also means FTS5 cannot see
# writes to `name` by itself, hence the three triggers below.
#
# The 'delete' command rows are the documented external-content contract: FTS5
# needs the OLD values to retract a posting, and omitting them silently corrupts
# the index rather than erroring.
# --------------------------------------------------------------------------

def _create_name_fts() -> None:
    op.execute("""
        CREATE VIRTUAL TABLE name_fts USING fts5(
            canonical_name,
            content='name',
            content_rowid='id',
            tokenize='unicode61 remove_diacritics 2'
        )
    """)
    op.execute("""
        CREATE TRIGGER name_fts_ai AFTER INSERT ON name BEGIN
            INSERT INTO name_fts(rowid, canonical_name)
            VALUES (new.id, new.canonical_name);
        END
    """)
    op.execute("""
        CREATE TRIGGER name_fts_ad AFTER DELETE ON name BEGIN
            INSERT INTO name_fts(name_fts, rowid, canonical_name)
            VALUES ('delete', old.id, old.canonical_name);
        END
    """)
    op.execute("""
        CREATE TRIGGER name_fts_au AFTER UPDATE ON name BEGIN
            INSERT INTO name_fts(name_fts, rowid, canonical_name)
            VALUES ('delete', old.id, old.canonical_name);
            INSERT INTO name_fts(rowid, canonical_name)
            VALUES (new.id, new.canonical_name);
        END
    """)


def _drop_name_fts() -> None:
    op.execute("DROP TRIGGER IF EXISTS name_fts_au")
    op.execute("DROP TRIGGER IF EXISTS name_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS name_fts_ai")
    op.execute("DROP TABLE IF EXISTS name_fts")


def downgrade() -> None:
    _drop_name_fts()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_track_track_id'))
        batch_op.drop_index(batch_op.f('ix_usage_track_release_id'))

    op.drop_table('usage_track')
    with op.batch_alter_table('change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_type'))
        batch_op.drop_index('ix_change_track')
        batch_op.drop_index('ix_change_pair_type')
        batch_op.drop_index('ix_change_pair')
        batch_op.drop_index(batch_op.f('ix_change_checklist_id'))

    op.drop_table('change')
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_release_status')
        batch_op.drop_index('ix_usage_release_name')
        batch_op.drop_index(batch_op.f('ix_usage_release_id'))
        batch_op.drop_index(batch_op.f('ix_usage_rank'))
        batch_op.drop_index('ix_usage_parent')
        batch_op.drop_index(batch_op.f('ix_usage_name_id'))
        batch_op.drop_index('ix_usage_accepted')

    op.drop_table('usage')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_checklist_id'))

    op.drop_table('track')
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_source_sha256'))
        batch_op.drop_index('ix_release_checklist_ordered')
        batch_op.drop_index(batch_op.f('ix_release_checklist_id'))

    op.drop_table('release')
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index('ix_link_to_name')
        batch_op.drop_index(batch_op.f('ix_link_from_name_id'))

    op.drop_table('link')
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_name_rank'))
        batch_op.drop_index('ix_name_genus_epithet')
        batch_op.drop_index(batch_op.f('ix_name_canonical_key'))
        batch_op.drop_index('ix_name_canonical')

    op.drop_table('name')
    op.drop_table('checklist')
    # ### end Alembic commands ###
